
DROP TABLE IF EXISTS liste_films, listes, journal, notes, casting, films, sagas, personnes, utilisateurs CASCADE;

CREATE TABLE sagas (
    id   INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nom  VARCHAR(60) NOT NULL UNIQUE
);

CREATE TABLE films (
    id                 INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    titre              VARCHAR(120) NOT NULL,
    annee              INTEGER      NOT NULL CHECK (annee BETWEEN 1888 AND 2100),
    genre              VARCHAR(30)  NOT NULL,
    saga_id            INTEGER REFERENCES sagas(id),
    film_precedent_id  INTEGER REFERENCES films(id)
);

CREATE TABLE personnes (
    id   INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nom  VARCHAR(80) NOT NULL UNIQUE
);

CREATE TABLE casting (
    film_id     INTEGER NOT NULL REFERENCES films(id),
    personne_id INTEGER NOT NULL REFERENCES personnes(id),
    role        VARCHAR(12) NOT NULL CHECK (role IN ('acteur', 'realisateur')),
    PRIMARY KEY (film_id, personne_id, role)
);

CREATE TABLE utilisateurs (
    id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pseudo      VARCHAR(30) NOT NULL UNIQUE,
    ville       VARCHAR(50),
    inscrit_le  DATE NOT NULL
);

CREATE TABLE notes (
    utilisateur_id INTEGER NOT NULL REFERENCES utilisateurs(id),
    film_id        INTEGER NOT NULL REFERENCES films(id),
    note           NUMERIC(2,1) NOT NULL CHECK (note BETWEEN 0.5 AND 5),
    note_le        DATE NOT NULL,
    PRIMARY KEY (utilisateur_id, film_id)
);

CREATE TABLE journal (
    id              INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    utilisateur_id  INTEGER NOT NULL REFERENCES utilisateurs(id),
    film_id         INTEGER NOT NULL REFERENCES films(id),
    date_visionnage DATE    NOT NULL
);

INSERT INTO sagas (nom) VALUES ('Retour vers le futur'), ('The Dark Knight'), ('X-Men : la prélogie');

INSERT INTO films (titre, annee, genre, saga_id) VALUES
 ('Apollo 13', 1995, 'Drame', NULL),
 ('Mystic River', 2003, 'Thriller', NULL),
 ('Des hommes d''honneur', 1992, 'Drame', NULL),
 ('X-Men : Le Commencement', 2011, 'Science-fiction', 3),
 ('X-Men : Days of Future Past', 2014, 'Science-fiction', 3),
 ('X-Men : Apocalypse', 2016, 'Science-fiction', 3),
 ('Forrest Gump', 1994, 'Drame', NULL),
 ('Seul au monde', 2000, 'Aventure', NULL),
 ('Il faut sauver le soldat Ryan', 1998, 'Guerre', NULL),
 ('Arrête-moi si tu peux', 2002, 'Policier', NULL),
 ('Titanic', 1997, 'Romance', NULL),
 ('Inception', 2010, 'Science-fiction', NULL),
 ('Les Infiltrés', 2006, 'Policier', NULL),
 ('Once Upon a Time… in Hollywood', 2019, 'Comédie', NULL),
 ('Le Loup de Wall Street', 2013, 'Comédie', NULL),
 ('Fight Club', 1999, 'Thriller', NULL),
 ('Ocean''s Eleven', 2001, 'Policier', NULL),
 ('Seven', 1995, 'Thriller', NULL),
 ('Batman Begins', 2005, 'Action', 2),
 ('The Dark Knight', 2008, 'Action', 2),
 ('The Dark Knight Rises', 2012, 'Action', 2),
 ('Les Évadés', 1994, 'Drame', NULL),
 ('Intouchables', 2011, 'Comédie', NULL),
 ('La Môme', 2007, 'Drame', NULL),
 ('The Artist', 2011, 'Comédie', NULL),
 ('Le Fabuleux Destin d''Amélie Poulain', 2001, 'Comédie', NULL),
 ('La Haine', 1995, 'Drame', NULL),
 ('Retour vers le futur', 1985, 'Science-fiction', 1),
 ('Retour vers le futur II', 1989, 'Science-fiction', 1),
 ('Retour vers le futur III', 1990, 'Science-fiction', 1);

UPDATE films SET film_precedent_id = 4  WHERE id = 5;
UPDATE films SET film_precedent_id = 5  WHERE id = 6;
UPDATE films SET film_precedent_id = 19 WHERE id = 20;
UPDATE films SET film_precedent_id = 20 WHERE id = 21;
UPDATE films SET film_precedent_id = 28 WHERE id = 29;
UPDATE films SET film_precedent_id = 29 WHERE id = 30;

CREATE TEMP TABLE _casting (film_id INTEGER, nom VARCHAR(80), role VARCHAR(12));
INSERT INTO _casting VALUES
 (1,'Tom Hanks','acteur'),(1,'Kevin Bacon','acteur'),(1,'Bill Paxton','acteur'),(1,'Gary Sinise','acteur'),(1,'Ed Harris','acteur'),(1,'Ron Howard','realisateur'),
 (2,'Sean Penn','acteur'),(2,'Tim Robbins','acteur'),(2,'Kevin Bacon','acteur'),(2,'Laurence Fishburne','acteur'),(2,'Clint Eastwood','realisateur'),
 (3,'Tom Cruise','acteur'),(3,'Jack Nicholson','acteur'),(3,'Demi Moore','acteur'),(3,'Kevin Bacon','acteur'),(3,'Rob Reiner','realisateur'),
 (4,'James McAvoy','acteur'),(4,'Michael Fassbender','acteur'),(4,'Jennifer Lawrence','acteur'),(4,'Kevin Bacon','acteur'),(4,'Matthew Vaughn','realisateur'),
 (5,'Hugh Jackman','acteur'),(5,'James McAvoy','acteur'),(5,'Michael Fassbender','acteur'),(5,'Jennifer Lawrence','acteur'),(5,'Omar Sy','acteur'),(5,'Bryan Singer','realisateur'),
 (6,'James McAvoy','acteur'),(6,'Michael Fassbender','acteur'),(6,'Jennifer Lawrence','acteur'),(6,'Bryan Singer','realisateur'),
 (7,'Tom Hanks','acteur'),(7,'Robin Wright','acteur'),(7,'Gary Sinise','acteur'),(7,'Robert Zemeckis','realisateur'),
 (8,'Tom Hanks','acteur'),(8,'Helen Hunt','acteur'),(8,'Robert Zemeckis','realisateur'),
 (9,'Tom Hanks','acteur'),(9,'Matt Damon','acteur'),(9,'Tom Sizemore','acteur'),(9,'Vin Diesel','acteur'),(9,'Steven Spielberg','realisateur'),
 (10,'Leonardo DiCaprio','acteur'),(10,'Tom Hanks','acteur'),(10,'Steven Spielberg','realisateur'),
 (11,'Leonardo DiCaprio','acteur'),(11,'Kate Winslet','acteur'),(11,'James Cameron','realisateur'),
 (12,'Leonardo DiCaprio','acteur'),(12,'Joseph Gordon-Levitt','acteur'),(12,'Elliot Page','acteur'),(12,'Tom Hardy','acteur'),(12,'Marion Cotillard','acteur'),(12,'Michael Caine','acteur'),(12,'Christopher Nolan','realisateur'),
 (13,'Leonardo DiCaprio','acteur'),(13,'Matt Damon','acteur'),(13,'Jack Nicholson','acteur'),(13,'Martin Scorsese','realisateur'),
 (14,'Leonardo DiCaprio','acteur'),(14,'Brad Pitt','acteur'),(14,'Margot Robbie','acteur'),(14,'Quentin Tarantino','realisateur'),
 (15,'Leonardo DiCaprio','acteur'),(15,'Jonah Hill','acteur'),(15,'Margot Robbie','acteur'),(15,'Jean Dujardin','acteur'),(15,'Martin Scorsese','realisateur'),
 (16,'Brad Pitt','acteur'),(16,'Edward Norton','acteur'),(16,'Helena Bonham Carter','acteur'),(16,'David Fincher','realisateur'),
 (17,'George Clooney','acteur'),(17,'Brad Pitt','acteur'),(17,'Matt Damon','acteur'),(17,'Julia Roberts','acteur'),(17,'Steven Soderbergh','realisateur'),
 (18,'Brad Pitt','acteur'),(18,'Morgan Freeman','acteur'),(18,'David Fincher','realisateur'),
 (19,'Christian Bale','acteur'),(19,'Michael Caine','acteur'),(19,'Liam Neeson','acteur'),(19,'Morgan Freeman','acteur'),(19,'Gary Oldman','acteur'),(19,'Christopher Nolan','realisateur'),
 (20,'Christian Bale','acteur'),(20,'Heath Ledger','acteur'),(20,'Michael Caine','acteur'),(20,'Morgan Freeman','acteur'),(20,'Gary Oldman','acteur'),(20,'Christopher Nolan','realisateur'),
 (21,'Christian Bale','acteur'),(21,'Tom Hardy','acteur'),(21,'Anne Hathaway','acteur'),(21,'Joseph Gordon-Levitt','acteur'),(21,'Marion Cotillard','acteur'),(21,'Michael Caine','acteur'),(21,'Gary Oldman','acteur'),(21,'Morgan Freeman','acteur'),(21,'Christopher Nolan','realisateur'),
 (22,'Tim Robbins','acteur'),(22,'Morgan Freeman','acteur'),(22,'Frank Darabont','realisateur'),
 (23,'François Cluzet','acteur'),(23,'Omar Sy','acteur'),(23,'Olivier Nakache','realisateur'),(23,'Éric Toledano','realisateur'),
 (24,'Marion Cotillard','acteur'),(24,'Gérard Depardieu','acteur'),(24,'Olivier Dahan','realisateur'),
 (25,'Jean Dujardin','acteur'),(25,'Bérénice Bejo','acteur'),(25,'Michel Hazanavicius','realisateur'),
 (26,'Audrey Tautou','acteur'),(26,'Mathieu Kassovitz','acteur'),(26,'Jean-Pierre Jeunet','realisateur'),
 (27,'Vincent Cassel','acteur'),(27,'Hubert Koundé','acteur'),(27,'Saïd Taghmaoui','acteur'),(27,'Mathieu Kassovitz','realisateur'),
 (28,'Michael J. Fox','acteur'),(28,'Christopher Lloyd','acteur'),(28,'Lea Thompson','acteur'),(28,'Robert Zemeckis','realisateur'),
 (29,'Michael J. Fox','acteur'),(29,'Christopher Lloyd','acteur'),(29,'Lea Thompson','acteur'),(29,'Robert Zemeckis','realisateur'),
 (30,'Michael J. Fox','acteur'),(30,'Christopher Lloyd','acteur'),(30,'Lea Thompson','acteur'),(30,'Robert Zemeckis','realisateur');

INSERT INTO personnes (nom) SELECT DISTINCT nom FROM _casting ORDER BY nom;
INSERT INTO casting (film_id, personne_id, role)
SELECT c.film_id, p.id, c.role FROM _casting c JOIN personnes p ON p.nom = c.nom;

INSERT INTO utilisateurs (pseudo, ville, inscrit_le) VALUES
 ('cinephile_92', 'Nanterre',  '2024-03-12'),
 ('popcorn_queen','Lyon',      '2024-09-01'),
 ('nolanfan',     'Paris',     '2025-01-05'),
 ('maxou_ciné',   'Marseille', '2025-02-20'),
 ('lea.reel',     'Lille',     '2025-04-02'),
 ('darkroom',     'Nantes',    '2025-06-18'),
 ('bobine',       'Bordeaux',  '2025-09-07'),
 ('sofa_critic',  'Paris',     '2025-12-11');

CREATE TEMP TABLE _base (film_id INTEGER, base NUMERIC);
INSERT INTO _base VALUES
 (1,3.8),(2,4.0),(3,3.6),(4,3.7),(5,3.9),(6,3.0),(7,4.4),(8,3.7),(9,4.3),(10,4.0),
 (11,3.9),(12,4.4),(13,4.2),(14,3.8),(15,4.1),(16,4.4),(17,3.6),(18,4.3),(19,3.9),(20,4.7),
 (21,3.9),(22,4.8),(23,4.3),(24,3.7),(25,3.8),(26,4.2),(27,4.3),(28,4.5),(29,3.9),(30,3.5);

CREATE TEMP TABLE _h AS
SELECT u.id AS utilisateur_id, b.film_id, b.base,
       ('x' || substr(md5(u.id || '-' || b.film_id), 1, 8))::bit(32)::int AS h
FROM utilisateurs u CROSS JOIN _base b;

INSERT INTO notes (utilisateur_id, film_id, note, note_le)
SELECT utilisateur_id, film_id,
       LEAST(5, GREATEST(0.5, ROUND((base + ((abs(h) % 11) - 5) * 0.15) * 2) / 2)),
       DATE '2026-01-05' + (abs(h / 7) % 255)
FROM _h
WHERE abs(h) % 3 <> 0;

INSERT INTO journal (utilisateur_id, film_id, date_visionnage)
SELECT utilisateur_id, film_id, note_le FROM notes;

INSERT INTO journal (utilisateur_id, film_id, date_visionnage)
SELECT n.utilisateur_id, n.film_id, n.note_le + 30 + (n.film_id % 20)
FROM notes n
WHERE n.note >= 4.5 AND n.note_le + 30 + (n.film_id % 20) <= DATE '2026-09-20';

DROP TABLE _casting, _base, _h;

SELECT 'films' AS table_name, COUNT(*) AS lignes FROM films
UNION ALL SELECT 'personnes', COUNT(*) FROM personnes
UNION ALL SELECT 'casting', COUNT(*) FROM casting
UNION ALL SELECT 'utilisateurs', COUNT(*) FROM utilisateurs
UNION ALL SELECT 'notes', COUNT(*) FROM notes
UNION ALL SELECT 'journal', COUNT(*) FROM journal;


DROP MATERIALIZED VIEW IF EXISTS mv_stats_films CASCADE;
DROP VIEW IF EXISTS v_fiche_film, v_films_sf CASCADE;
DROP FUNCTION IF EXISTS duree_texte(INTEGER), note_ponderee(INTEGER, INTEGER), compatibilite(TEXT, TEXT);
ALTER TABLE films DROP COLUMN IF EXISTS details CASCADE;

ALTER TABLE films ADD COLUMN details JSONB;

UPDATE films f
SET details = v.details::JSONB
FROM (VALUES
 ('Apollo 13',                            '{"duree": 140, "pays": ["États-Unis"], "langue": "anglais", "tags": ["espace", "histoire vraie"]}'),
 ('Mystic River',                         '{"duree": 138, "pays": ["États-Unis"], "langue": "anglais", "tags": ["enquête", "drame familial"]}'),
 ('Des hommes d''honneur',                '{"duree": 138, "pays": ["États-Unis"], "langue": "anglais", "tags": ["procès", "armée"]}'),
 ('X-Men : Le Commencement',              '{"duree": 132, "pays": ["États-Unis"], "langue": "anglais", "tags": ["super-héros", "mutants"]}'),
 ('X-Men : Days of Future Past',          '{"duree": 132, "pays": ["États-Unis"], "langue": "anglais", "tags": ["super-héros", "mutants", "voyage dans le temps"]}'),
 ('X-Men : Apocalypse',                   '{"duree": 144, "pays": ["États-Unis"], "langue": "anglais", "tags": ["super-héros", "mutants"]}'),
 ('Forrest Gump',                         '{"duree": 142, "pays": ["États-Unis"], "langue": "anglais", "tags": ["destin", "histoire américaine"], "oscar_meilleur_film": true}'),
 ('Seul au monde',                        '{"duree": 143, "pays": ["États-Unis"], "langue": "anglais", "tags": ["survie", "île"]}'),
 ('Il faut sauver le soldat Ryan',        '{"duree": 169, "pays": ["États-Unis"], "langue": "anglais", "tags": ["seconde guerre mondiale"]}'),
 ('Arrête-moi si tu peux',                '{"duree": 141, "pays": ["États-Unis"], "langue": "anglais", "tags": ["histoire vraie", "arnaque"]}'),
 ('Titanic',                              '{"duree": 194, "pays": ["États-Unis"], "langue": "anglais", "tags": ["romance", "naufrage"], "oscar_meilleur_film": true}'),
 ('Inception',                            '{"duree": 148, "pays": ["États-Unis", "Royaume-Uni"], "langue": "anglais", "tags": ["rêves", "braquage"]}'),
 ('Les Infiltrés',                        '{"duree": 151, "pays": ["États-Unis"], "langue": "anglais", "tags": ["mafia", "remake"], "oscar_meilleur_film": true}'),
 ('Once Upon a Time… in Hollywood',       '{"duree": 161, "pays": ["États-Unis"], "langue": "anglais", "tags": ["Hollywood", "années 60"]}'),
 ('Le Loup de Wall Street',               '{"duree": 180, "pays": ["États-Unis"], "langue": "anglais", "tags": ["histoire vraie", "finance"]}'),
 ('Fight Club',                           '{"duree": 139, "pays": ["États-Unis"], "langue": "anglais", "tags": ["culte", "twist"]}'),
 ('Ocean''s Eleven',                      '{"duree": 116, "pays": ["États-Unis"], "langue": "anglais", "tags": ["braquage", "Las Vegas"]}'),
 ('Seven',                                '{"duree": 127, "pays": ["États-Unis"], "langue": "anglais", "tags": ["enquête", "tueur en série", "twist"]}'),
 ('Batman Begins',                        '{"duree": 140, "pays": ["États-Unis", "Royaume-Uni"], "langue": "anglais", "tags": ["super-héros", "Gotham"]}'),
 ('The Dark Knight',                      '{"duree": 152, "pays": ["États-Unis", "Royaume-Uni"], "langue": "anglais", "tags": ["super-héros", "Gotham", "culte"]}'),
 ('The Dark Knight Rises',                '{"duree": 164, "pays": ["États-Unis", "Royaume-Uni"], "langue": "anglais", "tags": ["super-héros", "Gotham"]}'),
 ('Les Évadés',                           '{"duree": 142, "pays": ["États-Unis"], "langue": "anglais", "tags": ["prison", "amitié", "culte"]}'),
 ('Intouchables',                         '{"duree": 112, "pays": ["France"], "langue": "français", "tags": ["histoire vraie", "amitié"]}'),
 ('La Môme',                              '{"duree": 140, "pays": ["France"], "langue": "français", "tags": ["biopic", "musique"]}'),
 ('The Artist',                           '{"duree": 100, "pays": ["France"], "langue": "muet", "tags": ["cinéma muet", "Hollywood"], "oscar_meilleur_film": true}'),
 ('Le Fabuleux Destin d''Amélie Poulain', '{"duree": 122, "pays": ["France"], "langue": "français", "tags": ["Paris", "culte"]}'),
 ('La Haine',                             '{"duree": 98,  "pays": ["France"], "langue": "français", "tags": ["banlieue", "noir et blanc", "culte"]}'),
 ('Retour vers le futur',                 '{"duree": 116, "pays": ["États-Unis"], "langue": "anglais", "tags": ["voyage dans le temps", "culte"]}'),
 ('Retour vers le futur II',              '{"duree": 108, "pays": ["États-Unis"], "langue": "anglais", "tags": ["voyage dans le temps"]}'),
 ('Retour vers le futur III',             '{"duree": 118, "pays": ["États-Unis"], "langue": "anglais", "tags": ["voyage dans le temps", "western"]}')
) AS v(titre, details)
WHERE f.titre = v.titre;

ALTER TABLE films ALTER COLUMN details SET NOT NULL;

SELECT COUNT(*) AS films_avec_fiche,
       COUNT(*) FILTER (WHERE details ? 'oscar_meilleur_film') AS oscarises
FROM films;

DROP INDEX IF EXISTS idx_journal_profil, idx_journal_date,
                      idx_films_titre_trgm, idx_notes_film;

INSERT INTO films (titre, annee, genre, details)
SELECT (ARRAY['Le Dernier','La Nuit du','Les Enfants du','Le Secret du','La Chute du','Le Retour du',
              'L''Ombre du','La Légende du','Le Cri du','Les Gardiens du'])[1 + i % 10]
       || ' ' ||
       (ARRAY['Phare','Désert','Volcan','Marais','Glacier','Labyrinthe','Temple','Faubourg','Nord','Loup',
              'Cyclone','Pendule','Miroir','Canyon','Silence','Carrousel','Sablier','Brouillard','Récif','Métronome'])[1 + (i / 10) % 20]
       || ' ' || (1 + i / 200),
       1950 + (i * 7) % 76,
       (ARRAY['Drame','Comédie','Thriller','Science-fiction','Action','Policier','Romance','Aventure','Horreur','Animation'])[1 + (i * 3) % 10],
       jsonb_build_object('duree', 80 + (i * 13) % 100,
                          'tags', jsonb_build_array((ARRAY['culte','indé','festival','blockbuster','classique'])[1 + i % 5]))
FROM generate_series(1, 100000) AS i;

INSERT INTO utilisateurs (pseudo, ville, inscrit_le)
SELECT 'membre_' || i,
       (ARRAY['Paris','Lyon','Marseille','Lille','Nantes','Bordeaux','Toulouse','Rennes'])[1 + i % 8],
       DATE '2023-01-01' + (i * 37) % 1000
FROM generate_series(1, 20000) AS i;

INSERT INTO notes (utilisateur_id, film_id, note, note_le)
SELECT 8 + 1 + (i % 20000),
       1 + (i * 7919) % 100030,
       (1 + (i * 31) % 10) / 2.0,
       DATE '2025-01-01' + ((i * 13) % 630)::INTEGER
FROM generate_series(1::BIGINT, 1000000) AS i
ON CONFLICT DO NOTHING;

INSERT INTO journal (utilisateur_id, film_id, date_visionnage)
SELECT 8 + 1 + (i * 17) % 20000,
       1 + (i * 104729) % 100030,
       DATE '2025-01-01' + ((i * 7) % 630)::INTEGER
FROM generate_series(1::BIGINT, 1000000) AS i;

VACUUM ANALYZE films, utilisateurs, notes, journal;

SELECT 'films' AS table_name, COUNT(*) AS lignes FROM films
UNION ALL SELECT 'utilisateurs', COUNT(*) FROM utilisateurs
UNION ALL SELECT 'notes', COUNT(*) FROM notes
UNION ALL SELECT 'journal', COUNT(*) FROM journal;

DROP TABLE IF EXISTS films_stats, audit_notes CASCADE;
DROP PROCEDURE IF EXISTS noter(TEXT, TEXT, NUMERIC, NUMERIC), recalculer_stats(INTEGER);
DROP FUNCTION IF EXISTS trg_films_stats(), trg_audit_notes() CASCADE;

CREATE TABLE films_stats (
    film_id  INTEGER PRIMARY KEY REFERENCES films(id),
    nb_notes INTEGER NOT NULL,
    moyenne  NUMERIC(3,2) NOT NULL
);

CREATE TABLE audit_notes (
    id              INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    utilisateur_id  INTEGER NOT NULL,
    film_id         INTEGER NOT NULL,
    ancienne        NUMERIC(2,1),
    nouvelle        NUMERIC(2,1),
    le              TIMESTAMP NOT NULL DEFAULT now()
);

SELECT 'films_stats' AS table_name, COUNT(*) AS lignes FROM films_stats
UNION ALL SELECT 'audit_notes', COUNT(*) FROM audit_notes;

ALTER TABLE journal DISABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS journal_lecture ON journal;
DROP POLICY IF EXISTS journal_ecriture ON journal;
DROP FUNCTION IF EXISTS rechercher_films(TEXT);

DO $$
BEGIN
    IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'filmbox_app') THEN
        DROP OWNED BY filmbox_app;
        DROP ROLE filmbox_app;
    END IF;
END $$;

ALTER TABLE films DROP COLUMN IF EXISTS nb_vues;
ALTER TABLE films ADD COLUMN nb_vues INTEGER NOT NULL DEFAULT 0;

ALTER TABLE journal DROP COLUMN IF EXISTS prive;
ALTER TABLE journal ADD COLUMN prive BOOLEAN NOT NULL DEFAULT false;
UPDATE journal SET prive = true WHERE id % 4 = 0;

SELECT COUNT(*) AS entrees_journal,
       COUNT(*) FILTER (WHERE prive) AS entrees_privees
FROM journal;
